### ISSUE TITLE
how about helping a noob

### ISSUE THREAD

**Issue by jmartens2** [3DP-Tech/Kingroon-KP3#1]
hi im a bit confused by this. is there more detailed instructions?

**Comment by porrey** [comment]
I may plan to work on a video or more details in the future...  Before this makes sense you need to know how to compile Marlin. have you watched this video? https://www.youtube.com/watch?v=eq_ygvHF29I

**Comment by jmartens2** [comment]
I’ve done it a couple times. Mainly I figure I’m going to use your Marlin version. Then make the config changes and compile. But I kinda wanted to reach out and see if anyone was still around this work. Thank you for all you hard work and time! Thank you for returning my message. 
Jerry

**Comment by porrey** [comment]
Is your KP3 stock or modified?

**Comment by jmartens2** [comment]
Stock except glass bed. Filament detector. Upgrade the cooling fans. Nothing big. I’d like to try auto bed leveling some day.

**Comment by jmartens2** [comment]
Kind sir I will be retiring for the evening. Please stay healthy and happy.

**Comment by jmartens2** [comment]
Thank you for your help, sir! Have a great day and stay healthy!
